spring.application.name=spring-boot-config

#my.greetings=Hello world
app.description= welcome to ${spring.application.name}
my.list.values=one, two, three
dbValues={urlName: 'http://_____', username: 'myname', password: 'pass'}