spring.application.name=spring-boot-config

#my.greetings=Hello world
app.description= welcome to ${spring.application.name}
my.list.values=one, two, three
dbValues={urlName: 'http://_____', username: 'myname', password: 'pass'}

db.connection={url:'htpp://_____', username:'myname', password:'pass123'}
db.port=1234
db.host=0.123.01