spring:
  application:
    name: spring-boot-config
  config:
    import: configserver:http://localhost:8888

app:
  description: welcome to ${spring.application.name}

my:
  greetings: Hello world
  list:
    values: one, two, three
dbValues: "{urlName: 'http://_____', username: 'myname', password: 'pass'}"

db:
  connection: "{url:'htpp://_____', username:'myname', password:'pass123'}"
  port: 1234
  host: 0.123.01

management:
  endpoints:
    web:
      exposure.include: "*"

custom:
  value: this is custom value from the jar application.yml file

